name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up environment variables
        run: |
          echo "PUBLIC_IMAGES_CDN_HOST=${{ secrets.CLOUDFRONT_IMAGE_HOST }}" >> ./frontend/.env.production
          echo "PUBLIC_EMAIL_USER_ID=${{ secrets.EMAIL_USER_ID }}" >> ./frontend/.env.production
          echo "PUBLIC_EMAIL_SERVICE_ID=${{ secrets.EMAIL_SERVICE_ID }}" >> ./frontend/.env.production
          echo "PUBLIC_EMAIL_TEMPLATE_ID=${{ secrets.EMAIL_TEMPLATE_ID }}" >> ./frontend/.env.production
          echo "PUBLIC_POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}" >> ./frontend/.env.production
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install modules
        run: npm ci
        working-directory: ./frontend
      - name: Build application
        run: npm run build:ci
        working-directory: ./frontend
      - name: Deploy to S3
        run: aws s3 sync --delete ./frontend/dist/ s3://${{ secrets.BUCKET_ID }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
